### ISSUE TITLE
 Mongo DB can't be installed

### ISSUE THREAD

**Issue by slbejaranom** [google-coral/edgetpu#331]
Hello everyone, I have a server using nodejs mongo and dlib for tracking and counting cars, sending some info to mongo, however I have this running in docker, although I can get it out of docker it seems impossible to install mongo, i've tried some tricks from raspberry but still can't manage to do it, any help would be appreciated.

**Comment by mbrooksx** [comment]
Hello,

Can you provide information about how you attempted to install mongo and the errors that it produced?

Thanks!

**Comment by slbejaranom** [comment]
Well at first I tried like sudo apt-get install mongodb and it showed that there was no distribution for the armv8 processor, something like that if I remember well, after that, I tried building my docker-compose file and this is the one I'm talking about
```
version: "3"

services: 
  interfaz-web:
    build: ./webPage
    volumes:
      - ./webPage:/usr/src/app      
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

    ports:
      - 3000:3000
    depends_on: 
      - scriptfinal
      - mongo

  scriptfinal:
    build: ./scriptService
    volumes:
      - ./scriptService:/usr/src/scriptService      
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    devices:
      - /dev/video0:/dev/video0
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix      
    ports:
      - 3500:3500
    privileged: true
    depends_on: 
      - mongo

  mongo: 
    container_name: mongo
    image: mongo
    ports:
      - "6000:27017"
    logging: 
      driver: none

```
 
It didn't install mongo as there's no distribution available for the processor
