### ISSUE TITLE
Run on Kubernetes cluster

### ISSUE THREAD

**Issue by IArchi** [google-coral/edgetpu#488]
Given the `docker` command is (and works perfectly):

    sudo docker run -t -i --privileged -v /dev/bus/usb:/dev/bus/usb myCoralImage:latest

The `kubernetes` yaml file should looks like this:

    	apiVersion: apps/v1
	kind: DaemonSet
	metadata:
	  name: cameraai
	  labels:
		app.kubernetes.io/name: cameraai
		app.kubernetes.io/instance: cameraai
		app.kubernetes.io/version: "0.1"
	spec:
	  selector:
		matchLabels:
		  app.kubernetes.io/name: cameraai
		  app.kubernetes.io/instance: cameraai
	  template:
		metadata:
		  labels:
			app.kubernetes.io/name: cameraai
			app.kubernetes.io/instance: cameraai
		spec:
		  containers:
			- name: camera-ai
			  image: "myCoralImage:latest"
			  imagePullPolicy: Always
			  securityContext:
				privileged: true
			  volumeMounts:
				- name: dev-usb
				  mountPath: /dev/bus/usb
		  volumes:
			- name: dev-usb
			  hostPath:
				path: /dev/bus/usb

But this does not work. The **Coral Edge TPU** (USB Dongle) is not detected by the pod.

Is there any parameter to add to make it works ?

Thanks

**Comment by hjonnala** [comment]
can you try to follow [this](https://www.sodalite.eu/blog/deploying-across-heterogeneous-accelerators-edge-kubernetes) and see if it works..
```

apiVersion: v1
kind: Pod
metadata:
  name: http-echo-edgetpu-pod
  labels:
    app: http-echo
spec:
  containers:
  - name: http-echo
    image: adaptant/http-echo
    imagePullPolicy: IfNotPresent
    args: [ "-text", "hello from a node with an EdgeTPU" ]
    ports:
    - containerPort: 5678
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          # USB-attached Coral AI Accelerator
          - key: feature.node.kubernetes.io/usb-fe_1a6e_089a.present
            operator: In
            values: [ "true" ]
        - matchExpressions:
          # Coral Dev Board  
          - key: beta.devicetree.org/fsl-imx8mq-phanbell
            operator: In
            values: [ "1" ]
```
