### ISSUE TITLE
Cannot use the USB Coral in Docker

### ISSUE THREAD

**Issue by patrick-zinner** [google-coral/edgetpu#715]
### Description

Hi, 

I want to use the USB Edge TPU for Frigate running on Docker. The host machine runs Ubuntu 22.04.1 LTS. I did all the getting started stuff and `lsusb` shows:

```
Bus 002 Device 002: ID 1a6e:089a Global Unichip Corp.
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 0d8c:0014 C-Media Electronics, Inc. Audio Adapter (Unitek Y-247A)
Bus 001 Device 004: ID 0bda:c821 Realtek Semiconductor Corp. Bluetooth Radio
Bus 001 Device 003: ID 10c4:ea60 Silicon Labs CP210x UART Bridge
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

Sometimes it shows Google Inc. instead of the Global Unichip Corp. (probably after executing `make reset`).

Frigate runs using this docker compose configuration:

```
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    volumes:
      - /dev/bus/usb:/dev/bus/usb # also tried to use the devices section
      - /etc/localtime:/etc/localtime:ro
      - ./frigate/config/config.yml:/config/config.yml:ro
      - ./frigate/media:/media/frigate 
      - type: tmpfs 
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "hunter2"
```

When i connect to the container and execute `lsusb` then I get the following result:

```
Bus 002 Device 002: ID 1a6e:089a
Bus 002 Device 001: ID 1d6b:0003 Linux 5.15.0-58-generic xhci-hcd xHCI Host Controller
Bus 001 Device 005: ID 0d8c:0014 C-Media Electronics Inc. USB Audio Device
Bus 001 Device 004: ID 0bda:c821 Realtek  Bluetooth Radio
Bus 001 Device 003: ID 10c4:ea60 Silicon Labs Sonoff Zigbee 3.0 USB Dongle Plus
Bus 001 Device 001: ID 1d6b:0002 Linux 5.15.0-58-generic xhci-hcd xHCI Host Controller
```

When I configure the Coral as detector in Frigate, it starts up at first but then crashes because it cannot find the coral.

I've read several issues and threads here but all the solutions to previous problems do not work for me. Any idea what I can change?

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install, Support

### Operating System

Ubuntu

### Coral Device

USB Accelerator

### Relevant Log Output

_No response_</details>
